server:
  port: 8082

spring:
  application:
    name: ledger-core

  # --- DATABASE CONFIGURATION ---
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger_db
    username: ledger_user
    password: ledger_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- KAFKA CONFIGURATION ---
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ledger-group
      auto-offset-reset: earliest
      # Error handling deserializers prevent crashes on bad data
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Delegate to the actual deserializers
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        
        # FIX FOR GO INTEROP: Trust all packages and ignore type headers
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.Map
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer